import type { ReactNode } from "react";
import type { Profile } from "@/hooks/useProfile";
import { A4_WIDTH_PX } from "@/components/templates/a4";

/**
 * Branded A4 shell used by purchase orders, client statements and reports.
 * Uses inline styles only so html2canvas renders it identically everywhere.
 */

export interface PrintShellProps {
  profile: Profile | null;
  title: string;
  subtitle?: string;
  meta?: { label: string; value: string }[];
  generatedBy?: string;
  accent?: string;
  children: ReactNode;
  footerNote?: string;
}

const PrintShell = ({
  profile,
  title,
  subtitle,
  meta = [],
  generatedBy,
  accent = "#1A1A1A",
  children,
  footerNote,
}: PrintShellProps) => {
  const generatedAt = new Date().toLocaleString("en-ZA", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  return (
    <div
      style={{
        width: `${A4_WIDTH_PX}px`,
        minWidth: `${A4_WIDTH_PX}px`,
        backgroundColor: "#ffffff",
        color: "#1A1A1A",
        fontFamily: "Helvetica, Arial, sans-serif",
        boxSizing: "border-box",
        padding: "40px 44px 56px",
      }}
    >
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: "24px" }}>
        <div style={{ maxWidth: "58%" }}>
          {profile?.logo_url ? (
            <img
              src={profile.logo_url}
              alt={profile?.company_name || "Company logo"}
              crossOrigin="anonymous"
              style={{ maxHeight: "56px", maxWidth: "190px", objectFit: "contain", marginBottom: "10px", display: "block" }}
            />
          ) : null}
          <p style={{ margin: 0, fontSize: "15px", fontWeight: 700 }}>{profile?.company_name || "Your Company"}</p>
          {profile?.company_address ? (
            <p style={{ margin: "3px 0 0", fontSize: "10px", color: "#555555", whiteSpace: "pre-line", lineHeight: 1.4 }}>
              {profile.company_address}
            </p>
          ) : null}
          <p style={{ margin: "3px 0 0", fontSize: "10px", color: "#555555", lineHeight: 1.5 }}>
            {profile?.company_email ? <span>{profile.company_email}</span> : null}
            {profile?.company_phone ? <span> · {profile.company_phone}</span> : null}
            {profile?.company_website ? <span> · {profile.company_website}</span> : null}
          </p>
          {profile?.vat_number ? (
            <p style={{ margin: "3px 0 0", fontSize: "10px", color: "#555555" }}>VAT No: {profile.vat_number}</p>
          ) : null}
          {profile?.registration_number ? (
            <p style={{ margin: "2px 0 0", fontSize: "10px", color: "#555555" }}>Reg No: {profile.registration_number}</p>
          ) : null}
        </div>

        <div style={{ textAlign: "right", minWidth: "34%" }}>
          <p style={{ margin: 0, fontSize: "22px", fontWeight: 700, letterSpacing: "0.5px", color: accent }}>{title}</p>
          {subtitle ? <p style={{ margin: "4px 0 0", fontSize: "11px", color: "#555555" }}>{subtitle}</p> : null}
          <table style={{ marginLeft: "auto", marginTop: "10px", borderCollapse: "collapse" }}>
            <tbody>
              {meta.map((row) => (
                <tr key={`${row.label}-${row.value}`}>
                  <td style={{ padding: "2px 8px 2px 0", fontSize: "10px", color: "#777777", textAlign: "right" }}>
                    {row.label}
                  </td>
                  <td style={{ padding: "2px 0", fontSize: "10px", fontWeight: 600, textAlign: "right" }}>{row.value}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div style={{ height: "3px", backgroundColor: accent, margin: "18px 0 20px" }} />

      <div>{children}</div>

      <div style={{ marginTop: "28px", borderTop: "1px solid #E5E5E5", paddingTop: "8px" }}>
        <p style={{ margin: 0, fontSize: "9px", color: "#888888" }}>
          Generated: {generatedAt}
          {generatedBy ? ` · Generated by: ${generatedBy}` : ""}
        </p>
        {footerNote ? <p style={{ margin: "3px 0 0", fontSize: "9px", color: "#888888" }}>{footerNote}</p> : null}
      </div>
    </div>
  );
};

export default PrintShell;
